apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp
  labels:
    name: simple-webapp
spec:
  containers:
    - name: simple-webapp
      image: simple-webapp
      ports:
        - containerPort: 8080
      readinessProbe: # three types of readiness probes
        httpGet:
          path: /api/ready
          port: 8080
        initialDelaySeconds: 5 # wait for 5 seconds before starting the probe
        periodSeconds: 5 # probe every 5 seconds
        failureThreshold: 8 # consider the probe failed after 8 attempts
        tcpSocket:
          port: 8080
        exec:
          command:
            - cat
            - /app/is_ready
